# Generated by Django 5.1.4 on 2024-12-13 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('pkInt', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('pkInt', models.IntegerField(primary_key=True, serialize=False)),
                ('changeDate', models.DateField()),
                ('previousSalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currentSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changeReason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('pkInt', models.IntegerField(primary_key=True, serialize=False)),
                ('jobPositionName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pkInt', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('hireDate', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('jobPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobposition')),
                ('salaryHistory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.salaryhistory')),
            ],
        ),
    ]
