# Generated by Django 5.1.4 on 2024-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_department_departmentname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='precio',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedido',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idCliente',
            field=models.IntegerField(),
        ),
    ]
